### ISSUE TITLE
Mobile app integration

### ISSUE THREAD

**Issue by nikhil19rathore99** [kartik2112/Silatra#83]
Can we use directly this model to run in local machine and use api call to get the output on mobile screen??

**Comment by nikhil19rathore99** [comment]
/home/nikhil/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "Receiver.py", line 31, in <module>
    from sklearn.neighbors import KNeighborsClassifier
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 13, in <module>
    from .validation import (as_float_array,
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 27, in <module>
    from ..utils._joblib import Memory
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/utils/_joblib.py", line 18, in <module>
    from ..externals.joblib import __all__   # noqa
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/externals/joblib/parallel.py", line 32, in <module>
    from .externals.cloudpickle import dumps, loads
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 151, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/nikhil/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 132, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
got this error??

**Comment by nikhil19rathore99** [comment]
I've tried scikit-learn==0.20 but same error occurs
